# -*- coding: utf-8 -*-
"""logistic regression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jPK9zfyib_j35NQHwRZFklvF2Fl4GeRk
"""

print("Hello World !")

import pandas as pd 
import matplotlib.pyplot as plt
import numpy as np

from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix

from google.colab import files
import io
uploaded = files.upload()

data = pd.read_csv(io.BytesIO(uploaded['Reg-log_offre.csv']))

data.head()

data['Gender']=data['Gender'].replace({'Female':0, 'Male':1})

data

X = data.iloc[:,:-1]
y = data.iloc[:, -1]
X_train, X_test, y_train, y_test=train_test_split(X,y,test_size=0.2, random_state=42)

model = LogisticRegression()

model.fit(X_train,y_train)

y_pred = model.predict(X_test)

comp = pd.DataFrame(y_pred,y_test)
comp

print("Accuracy :", accuracy_score(y_test,y_pred))

print("confusion matrix : ")
print(confusion_matrix(y_test,y_pred))